from typing import Any      # Available in Python 3.5+
from typing import Final    # Available in Python 3.8+
from collections.abc import MutableMapping, Mapping, MutableSequence, Sequence, Iterable
from numpy.typing import ArrayLike, NDArray

# All variable lists should be taken as non-exhaustive

transp_dimensions: Final[Mapping[str, tuple[str, ...]]] = {
    'time': ('', 'plasma time'),
    'x': ('', 'r/a cell centres'),
    'xb': ('', 'r/a cell boundaries'),
    'iasym': ('', 'shaping coefficient index'),
}
transp_coordinates: Final[Mapping[str, tuple[str, ...]]] = {
    'rzon': ('cm', 'zone radius'),
    'rboun': ('cm', 'boundary radius'),
    'rmajb': ('cm', 'major radius boundary'),
    'rmnmp': ('cm', 'minor radius midplane'),
    'rmjmp': ('cm', 'major radius centroid midplane'),
    'ympa': ('cm', 'vertical position'),
    #'ympbdy': ('', 'vertical position boundary'),
    'raxis': ('cm', 'major radius of magnetic axis'),
    'yaxis': ('cm', 'vertical position of magnetic axis'),
    'darea': ('cm**2', 'zone cross-sectional area'),
    'dvol': ('cm**3', 'zone volume'),
    'surf': ('cm**2', 'flux surface area'),
    'lpol': ('cm', 'poloidal path length'),
    #'pvol': ('cm**3', 'integrated volume'),
    #'parea': ('cm**2', 'integrated cross-sectional area'),
}
transp_geometry: Final[Mapping[str, tuple[str, ...]]] = {
    'gri': ('cm**-1', 'flux-surface-average 1/R'),
    'gr2': ('cm**2', 'flux-surface-average R**2'),
    'gr2i': ('cm**-2', 'flux-surface-average 1/R**2'),
    'gr2x2': ('', 'flux-surface-average R**2*grad(x)**2'),
    'gx2r2i': ('cm**-4', 'flux-surface-average grad(x)**2/R**2'),
    'grixi': ('', 'flux-surface-average 1/(R*grad(x))'),
    'gxi': ('cm**-1', 'flux-surface-average grad(x)'),
    'gxi2': ('cm**-2', 'flux-surface-average grad(x)**2'),
    'drav': ('cm', 'flux-surface-average dR'),
    'dravfac': ('', '<dR> * <1/dR>'),
    'gbr2': ('T cm**2', 'flux-surface-average B*R**2'),
    'gb1': ('T', 'flux-surface-average B'),
    'gb2': ('T**2', 'flux-surface-average B**2'),
    'gb2i': ('T**-2', 'flux-surface-average 1/B**2'),
    'gx2b2i': ('T**-2 cm**-2', 'flux-surface-average grad(x)**2/B**2'),
    'jgphr2i': ('A cm**-1', '<J.grad(phi)> / <1/R**2>'),
    'arat': ('', 'aspect ratio'),
    'elong': ('', 'flux surface elongation'),
    'triang': ('', 'flux surface triangularity'),
    'triangu': ('', 'flux surface upper triangularity'),
    'triangl': ('', 'flux surface lower triangularity'),
    'square_uo': ('', 'flux surface upper outer squareness'),
    'square_lo': ('', 'flux surface lower outer squareness'),
    'sshaf': ('', 'Shafranov shift'),
    #'ashaf': ('', 'Shafranov shift of magnetic axis'),
}
transp_geometric_moment: Final[Mapping[str, tuple[str, ...]]] = {
    'rmc': ('', 'R cosine moment'),
    'ymc': ('', 'Z cosine moment'),
    'rms': ('', 'R sine moment'),
    'yms': ('', 'Z sine moment'),
    'rmcb': ('', 'R cosine moment boundary'),
    'ymcb': ('', 'Z cosine moment boundary'),
    'rmsb': ('', 'R sine moment boundary'),
    'ymsb': ('', 'Z sine moment boundary'),
}
transp_magnetics: Final[Mapping[str, tuple[str, ...]]] = {
    'bpol': ('T', 'poloidal magnetic field'),
    'bz': ('T', 'vertical magnetic field at outer midplane'),
    'cur': ('A cm**-2', 'total plasma current density'),
    'curoh': ('A cm**-2', 'ohmic plasma current density'),
    'curxt': ('A cm**-2', 'externally-driven plasma current density'),
    'pljb': ('A T cm**-2', 'flux-surface-average j.B'),
    'pljbxoh': ('A T cm**-2', 'flux-surface-average ohmic j.B'),
    'pljbxt': ('A T cm**-2', 'flux-surface-average externally-driven j.B'),
    #'pljbxtr': ('A T cm**-2', 'flux-surface-average resistive j.B'),
    #'pljbsnc': ('A T cm**-2', 'flux-surface-average neoclassical bootstrap j.B'),
    #'pljbsneo': ('A T cm**-2', 'flux-surface-average NEO-GK bootstrap j.B'),
    #'pljbbgpi': ('', ''),
    'v': ('V', 'voltage'),
    'vpoh': ('V', 'voltage for ohmic calculations'),
    'poh': ('W cm**-3', 'ohmic heating power'),
    #'poht': ('W', 'total ohmic input power'),
    #'ipxvs': ('W', 'flux surface power'),
    'plflx': ('Wb rad**-1', 'poloidal flux'),
    'trflx': ('Wb', 'toroidal flux'),
    #'plflxa': ('Wb rad**-1', 'enclosed poloidal flux'),
    #'tflux': ('Wb', 'enclosed toroidal flux'),
    'curbs': ('A cm**-2', 'bootstrap current density'),
    #'curbsneo': ('A cm**-2', 'NEO-GK bootstrap current density'),
    #'curbshag': ('A cm**-2', 'Hager bootstrap current density'),
    #'curbswnc': ('A cm**-2', 'NCLASS bootstrap current density'),
    #'curbseps': ('A cm**-2', 'aspect ratio bootstrap current density'),
    'eta_use': ('Ohm cm', 'resistivity used in TRANSP calculations'),
    #'eta_nc': ('Ohm cm', 'neoclassical resistivity'),
    #'eta_sp': ('Ohm cm', 'Spitzer resistivity'),
    #'eta_sps': ('Ohm cm', 'Sauter Spitzer resistivity'),
    #'eta_wnc': ('Ohm cm', 'NCLASS resistivity'),
    #'eta_tsc': ('Ohm cm', 'TSC neoclassical resistivity'),
    #'eta_snc': ('Ohm cm', 'Sauter neoclassical resistivity'),
    #'dflux': ('Wb', 'diamagnetic flux'),
    #'dflxm': ('Wb', 'measured diamagnetic flux'),
    'lio2c': ('', 'internal inductance li/2 from current profile'),
    #'lio2': ('', 'internal inductance li/2'),
    #'lio2m': ('', 'internal inductance li/2 from magnetics measurements'),
    'li_3': ('', 'internal inductance, ITER definition'),
    #'li_1': ('', 'internal inductance'),
    #'li_vdiff': ('', 'internal inductance from voltage difference'),
    'li2pb': ('', 'internal inductance li/2 + beta poloidal'),
    'betae': ('', 'electron beta poloidal'),
    'betai': ('', 'thermal ion beta poloidal'),
    'betat': ('', 'total beta poloidal'),
    'betar': ('', 'rotation beta poloidal'),
    'bbeta': ('', 'beam beta poloidal'),
    'bte': ('', 'electron beta toroidal'),
    'bti': ('', 'thermal ion beta toroidal'),
    'bttot': ('', 'total beta toroidal'),
    'btrot': ('', 'rotation beta toroidal'),
    'btbe': ('', 'beam beta toroidal'),
    #'btpl': ('', 'plasma beta toroidal'),
    'btal': ('', 'alpha beta toroidal'),
}
transp_species: Final[Mapping[str, tuple[str, ...]]] = {
    'xzimpj': ('', 'zone average impurity charge'),
    'aimpj': ('', 'zone average impurity mass number'),
    'zimps_tok': ('', 'average impurity charge from TOK'),
}
transp_profiles: Final[Mapping[str, tuple[str, ...]]] = {
    'q': ('', 'safety factor'),
    'shat': ('', 'magnetic shear (r/q)*(dq/dr)'),
    'qp': ('', 'safety factor profile'), # What?
    'ne': ('cm**-3', 'electron density'),
    'te': ('eV', 'electron temperature'),
    'ni': ('cm**-3', 'total ion density'),
    'ti': ('eV', 'ion temperature'),
    'tipro': ('eV', 'measured ion temperature'),
    'pplas': ('Pa', 'plasma pressure'),
    'nimp': ('cm**-3', 'impurity ion density'),
    'nimps_tok': ('cm**-3', 'impurity ion density from TOK'),
    'tx': ('eV', 'impurity ion temperature'),
    'zeffp': ('', 'effective charge'),
    #'tmj': ('eV', 'minority ion temperature'),
    #'tmjsm': ('eV', 'minority ion temperature smoothed'),
    #'tiav': ('eV', 'averaged ion temperature including minority'),
    #'nd': ('', ''),
    'nalpha': ('cm**-3', 'alpha ion density'),
    'vtormp': ('cm s**-1', 'toroidal velocity on outer midplane'),
    'vpolmp': ('cm s**-1', 'poloidal velocity on outer midplane'),
    'omgnc': ('rad s**-1', 'neoclassical toroidal angular velocity'),
    'omega': ('rad s**-1', 'toroidal angular velocity'),
    'omega_nc': ('rad s**-1', 'neoclassical toroidal angular velocity'), # Duplicated?
    'nusti': ('', 'ion normalized collisionality'),
    'nuste': ('', 'electron normalized collisionality'),
    'cloge': ('', 'electron coulomb logarithm'),
    'clogi': ('', 'ion coulomb logarithm'),
    'etae': ('', 'logarithmic electron temperature gradient by logarithmic electron density gradient'),
    'etai': ('', 'logarithmic ion temperature gradient by logarithmic ion density gradient'),
    'etaie': ('', 'logarithmic ion temperature gradient by logarithmic electron density gradient'),
    'srexba': ('rad s**-1', 'ExB shearing rate'),
    'srexbphi': ('rad s**-1', 'ExB shearing rate from toroidal velocity'),
    'srexbtht': ('rad s**-1', 'ExB shearing rate from poloidal velocity'),
    'srexbgrp': ('rad s**-1', 'ExB shearing rate from pressure gradient'),
    #'srexbmod': ('rad s**-1', 'ExB shearing rate in transport model'),
    'vrpot': ('V', 'radial electric potential'),
    'epotro': ('V', 'radial electric potential from rotation velocity'),
}
transp_globals: Final[Mapping[str, tuple[str, ...]]] = {
    'voltsec0': ('V s', 'axial flux consumption'),
    #'voltsec': ('V s', 'volt-second flux consumption'),
    'tauea': ('s', 'thermal energy confinement time'),
    'taua1': ('s', 'total energy confinement time'),
    #'tauee': ('s', 'electron energy confinement time'),   # old?
    'tee': ('s', 'electron energy confinement time'),
    'teest': ('', 'normalized electron energy confinement time'),
    'tei': ('s', 'ion energy confinement time'),
    'teist': ('', 'normalized ion energy confinement time'),
    'taupe': ('s', 'electron particle confinement time'),
    'tapwe': ('s', 'electron particle confinement time Ware correction'),
    'taupi': ('s', 'ion energy confinement time'),
    #'taupd': ('s', 'deuterium particle confinement time'),
    'tauphi': ('s', 'momentum confinement time'),
    'taue': ('s', 'plasma energy confinement time'),
    'taues': ('s', 'normalized plasma energy confinement time'),
    'taue98y1': ('s', 'energy confinement time from 98y,1 scaling'),
    'taue98y2': ('s', 'energy confinement time from 98y,2 scaling'),
    #'taue89p': ('s', 'energy confinement time from 89P scaling'),
    #'taue97lg': ('s', 'energy confinement time from 97L,g scaling'),
    #'taue97lth': ('s', 'energy confinement time from 97L,th scaling'),
    #'tauest06': ('s', 'energy confinement time from ST06 scaling'),
    'h98y1': ('', 'confinement factor against 98y,1 scaling'),
    'h98y2': ('', 'confinement factor against 98y,2 scaling'),
    #'h89p': ('', 'confinement factor against 89P scaling'),
    #'h97lg': ('', 'confinement factor against 97L,g scaling'),
    #'h97lth': ('', 'confinement factor against 97L,th scaling'),
    #'hst06': ('', 'confinement factor against ST06 scaling'),
    'pl2hreq': ('W', 'L-H transition power'),
    'pl2htot': ('W', 'total heating power'),
    #'lhmode': ('', 'H-mode indicator'),
    'bplim': ('W', 'fast ion orbit energy loss rate'),
    'bpth': ('W', 'thermalized fast ion power'),
    'bpst': ('W', 'stored fast ion power'),
    'bsorb': ('s**-1', 'fast ion orbit particle loss rate'),
    'bsth': ('s**-1', 'fast ion thermalization rate'),
    'bdndt': ('s**-1', 'fast ion population change rate'),
    'neutt': ('s**-1', 'total neutron generation rate'),
    'neutx': ('s**-1', 'neutron generation rate from thermal reactions'),
}
transp_transport: Final[Mapping[str, tuple[str, ...]]] = {
    #'gaine': ('', ''),
    #'eheat': ('', ''),
    #'pcnve': ('', ''),
    #'pcnde': ('', ''),
    #'dnedt': ('', ''),
    #'divfe': ('', ''),
    #'scew': ('', ''),
    #'scev': ('', ''),
    #'scez': ('', ''),
    #'dnidt': ('', ''),
    #'divfi': ('', ''),
    #'sbtot': ('', ''),
    #'swtot': ('', ''),
    #'sbal_ion': ('', ''),
    #'dnimp': ('', ''),
    #'dfimp': ('', ''),
    #'scimp': ('', ''),
    #'dzimp': ('', ''),
    #'dnddt': ('', ''),
    #'divfd': ('', ''),
    #'svd': ('', ''),
    #'swd': ('', ''),
    #'sbal_d': ('', ''),
    #'mdot': ('', ''),
    #'tqin': ('', ''),
    #'mconv': ('', ''),
    #'mvisc': ('', ''),
    #'m0net': ('', ''),
    #'tibal': ('', ''),
    #'tebal': ('', ''),
    #'phbal': ('', ''),
    #'bpbal': ('', ''),
    #'bsbal': ('', ''),
    #'bphck': ('', ''),
    #'bpbal_d': ('', ''),
    #'bsbal_d': ('', ''),
    #'bphck_d': ('', ''),
    #'p0bal': ('', ''),
}
transp_sources: Final[Mapping[str, tuple[str, ...]]] = {
    'qie': ('W cm**-3', 'ion-electron equipartition power density'),
    'qrot': ('W cm**-3', 'ion heat density from rotational stress'),
    'gasd': ('s**-1', 'deuterium neutral gas particle flow rate'),
    'rcyd': ('s**-1', 'deuterium recycling particle flow rate'),
    'tqin': ('N m cm**-3', 'total injection torque'),
    'tqntv': ('N m cm**-3', 'torque from neoclassical toroidal viscosity'),
    'prad': ('W cm**-3', 'energy source density from radiation'),
    'prad_br': ('W cm**-3', 'energy source density from Bremsstrahlung radiation'),
    'prad_li': ('W cm**-3', 'energy source density from line radiation'),
    'prad_cy': ('W cm**-3', 'energy source density from cyclotron radiation'),
    'pion': ('W cm**-3', 'energy source density from ionization'),
    'prads_tok': ('W cm**-3', 'energy source density from TOK radiation'),
    'prls_tok': ('W cm**-3', 'energy source density from TOK line radiation'),
    'prbs_tok': ('W cm**-3', 'energy source density from TOK Bremsstrahlung radiation'),
    'pni': ('W cm**-3', 'neutral ionization energy source density'),
    'sbtot': ('cm**-3 s**-1', 'total ion particle source density (beam + halo)'),
    'sbe': ('cm**-3 s**-1', 'electron particle source density from neutral beam'),
    'sbth': ('cm**-3 s**-1', 'ion particle source density from neutral beam fast ion thermalization'),
    'pbe': ('W cm**-3', 'electron energy source density from neutral beam'),
    'pbi': ('W cm**-3', 'ion energy source density from neutral beam'),
    'pbth': ('W cm**-3', 'ion energy source density from neutral beam fast ion thermalization'),
    #'sbe_d': ('cm**-3 s**-1', 'electron particle source density from deuterium neutral beam'),
    #'sbth_d': ('cm**-3 s**-1', 'ion particle source density from deuterium neutral beam fast ion thermalization'),
    #'pbe_d': ('W cm**-3', 'electron energy source density from deuterium neutral beam'),
    #'pbi_d': ('W cm**-3', 'ion energy source density from deuterium neutral beam'),
    #'pbth_d': ('W cm**-3', 'ion energy source density from deuterium neutral beam fast ion thermalization'),
    #'sdbbi': ('cm**-3 s**-1', ''),
    #'sdbbx': ('cm**-3 s**-1', ''),
    #'sdb_ii': ('cm**-3 s**-1', ''),
    #'sdb_ie': ('cm**-3 s**-1', ''),
    #'sdb_iz': ('cm**-3 s**-1', ''),
    'omegb': ('rad s**-1', 'average ion angular velocity of neutral beam'),
    'tqbe': ('N m cm**-3', 'electron torque from neutral beam'),
    'tqbi': ('N m cm**-3', 'ion torque from neutral beam'),
    'tqbco': ('N m cm**-3', 'collisional torque from neutral beam'),
    'tqbth': ('N m cm**-3', 'thermalization torque from neutral beam'),
    'tqjxb': ('N m cm**-3', 'JxB torque from neutral beam'),
    'tqbcx': ('N m cm**-3', 'charge exchange anti-torque from neutral beam'),
    #'tqohb': ('', ''),
    #'tqxfr': ('', ''),
    'pbtotnb': ('W cm**-3', 'total energy source density from neutral beam'),
    'pbenb': ('W cm**-3', 'total electron energy source density from neutral beam'),
    'pbinb': ('W cm**-3', 'total ion energy source density from neutral beam'),
    'pbthnb': ('W cm**-3', 'total thermalization energy source density from neutral beam'),
    'bdensnb': ('cm**-3', 'total density from neutral beam'),
    'bdepnb': ('cm**-3 s**-1', 'total particle source density from neutral beam'),
    'tqtotnb': ('N m cm**-3', 'total torque from neutral beam'),
    'tqcolnb': ('N m cm**-3', 'total collisional torque from neutral beam'),
    'tqthnb': ('N m cm**-3', 'total thermalization torque from neutral beam'),
    'tqjbnb': ('N m cm**-3', 'total JxB torque from neutral beam'),
    'tqjbnbd': ('N m cm**-3', 'total JxB torque deposited from neutral beam'),
    #'peech': ('', ''),
    #'eccur': ('', ''),
    #'piich': ('', ''),
    #'peich': ('', ''),
    #'iccur': ('', ''),
    #'nmini': ('', ''),
    'uthrm': ('J cm**-3', 'thermal energy density'),
    'ufastpp': ('J cm**-3', 'perpendicular fast ion energy density'),
    'ufastpa': ('J cm**-3', 'parallel fast ion energy density'),
    'ualphpp': ('J cm**-3', 'perpendicular fast alpha energy density'),
    'ualphpa': ('J cm**-3', 'parallel fast alpha energy density'),
    'tausal': ('s', 'fast alpha slowing down time'),
    'sceal': ('cm**-3 s**-1', 'fast alpha source density from fusion reactions'),
    'pale': ('W cm**-3', 'electron energy source density from fast alpha thermalization'),
    'pali': ('W cm**-3', 'ion energy source density from fast alpha thermalization'),
    'thntx': ('cm**-3 s**-1', 'neutron source density from thermal reactions'),
    'ttntx': ('cm**-3 s**-1', 'total neutron source density'),
}
transp_fluxes: Final[Mapping[str, tuple[str, ...]]] = {
    #'iptr': ('cm**-3 s**-1', 'ion particle transport'),
    #'eptr': ('cm**-3 s**-1', 'electron particle transport'),
    #'xptr': ('cm**-3 s**-1', 'impurity particle transport'),
    #'ietr': ('W cm**-3', 'ion energy transport'),
    #'eetr': ('W cm**-3', 'electron energy transport'),
    #'amtr': ('N m cm**-3', 'angular momentum transport'),
    #'iptr_mod': ('cm**-3 s**-1', 'ion particle transport from model'),
    #'eptr_mod': ('cm**-3 s**-1', 'electron particle transport from model'),
    #'xptr_mod': ('cm**-3 s**-1', 'impurity particle transport from model'),
    #'ptrd_mod': ('cm**-3 s**-1', 'deuterium particle transport from model'),
    #'ietr_mod': ('W cm**-3', 'ion energy transport from model'),
    #'eetr_mod': ('W cm**-3', 'electron energy transport from model'),
    #'amtr_mod': ('N m cm**-3', 'angular momentum transport from model'),
    'iptr_obs': ('cm**-3 s**-1', 'ion particle transport from observations'),
    'eptr_obs': ('cm**-3 s**-1', 'electron particle transport from observations'),
    'xptr_obs': ('cm**-3 s**-1', 'impurity particle transport from observations'),
    #'ptrd_obs': ('cm**-3 s**-1', 'deuterium particle transport from observations'),
    'ietr_obs': ('W cm**-3', 'ion energy transport from observations'),
    'eetr_obs': ('W cm**-3', 'electron energy transport from observations'),
    'amtr_obs': ('N m cm**-3', 'angular momentum transport from observations'),
    'gflnc_e': ('cm**-3 s**-1', 'electron particle transport from neoclassical model'),
    'qflnc_e': ('W cm**-3', 'electron energy transport from neoclassical model'),
    'qflncc_e': ('W cm**-3', 'electron energy transport from NCLASS model'),
    'gflnc_i': ('cm**-3 s**-1', 'ion particle transport from neoclassical model'),
    'qflnc_i': ('W cm**-3', 'ion energy transport from neoclassical model'),
    'qflncc_i': ('W cm**-3', 'ion energy transport from NCLASS model'),
    'gflnc_x': ('cm**-3 s**-1', 'impurity particle transport from neoclassical model'),
    'qflnc_x': ('W cm**-3', 'impurity energy transport from neoclassical model'),
    'qflncc_x': ('W cm**-3', 'impurity energy transport from NCLASS model'),
    #'gflnc_d': ('cm**-3 s**-1', 'deuterium particle transport from neoclassical model'),
    #'qflnc_d': ('W cm**-3', 'deuterium energy transport from neoclassical model'),
    #'qflncc_d': ('W cm**-3', 'deuterium energy transport from NCLASS model'),
}
transp_equilibrium: Final[Mapping[str, tuple[str, ...]]] = {
    'rgrid': ('cm', 'radial grid points for equilibrium poloidal flux map'),
    'zgrid': ('cm', 'vertical grid points for equilibrium poloidal flux map'),
    'psirz': ('Wb rad**-1', 'equilibrium poloidal flux map'),
}
transp_metadata: Final[Mapping[str, tuple[str, ...]]] = {
    'teped': ('eV', 'electron pedestal temperature'),
    'tiped': ('eV', 'ion pedestal temperature'),
    'neped': ('cm**-3', 'electron pedestal density'),
    'tepedw': ('', 'electron temperature pedestal width'),
    'tipedw': ('', 'ion temperature pedestal width'),
    'nepedw': ('', 'electron density pedestal width'),
    #'sc_teped': ('', 'electron pedestal temperature scaling factor'),
    #'sc_tiped': ('', 'ion pedestal temperature scaling factor'),
    #'sc_neped': ('', 'electron pedestal density scaling factor'),
    #'upwind_te': ('', 'electron energy balance upwind adjustment factor'),
    #'upwind_ti': ('', 'ion energy balance upwind adjustment factor'),
    #'upwind_mo': ('', 'momentum balance upwind adjustment factor'),
    #'upwind_d': ('', 'deuterium energy balance upwind adjustment factor'),
    #'sx_te': ('', 'electron energy balance solver range'),
    #'sx_ti': ('', 'ion energy balance solver range'),
    #'sx_ne': ('', 'electron particle balance solver range'),
    #'sx_omega': ('', 'angular momentum balance solver range'),
    #'nptriter': ('', 'number of Newton iterations in solution'),
    'tr_year': ('', 'year label of TRANSP release'),
    'tr_majv': ('', 'major version number of TRANSP release'),
    'trminv': ('', 'minor version number of TRANSP release'),
    'run': ('', 'run number'),
}
transp_base_variables: Final[Mapping[str, tuple[str, ...]]] = {
    **transp_dimensions,
    **transp_coordinates,
    **transp_geometry,
    **transp_geometric_moment,
    **transp_magnetics,
    **transp_species,
    **transp_profiles,
    **transp_globals,
    **transp_transport,
    **transp_sources,
    **transp_fluxes,
    **transp_equilibrium,
    **transp_metadata,
}


gacode_single_line_integer: Final[Mapping[str, tuple[str, ...]]] = {
    'nexp': ('', 'number of radial points'),
    'nion': ('', 'number of ion species'),
    'shot': ('', 'shot number'),
}
gacode_single_line_string: Final[Mapping[str, tuple[str, ...]]] = {
    'name': ('', 'ion species periodic table symbol'),
    'type': ('', 'ion species type'),
}
gacode_single_line_float: Final[Mapping[str, tuple[str, ...]]] = {
    'masse': ('', 'electron mass number'),
    'mass': ('', 'ion mass number'),
    'ze': ('', 'electron charge number'),
    'z': ('', 'ion charge number'),
    'torfluxa': ('Wb rad**-1', 'toroidal flux'),
    'rcentr': ('m', 'radial position of magnetic axis'),
    'bcentr': ('T', 'magnetic field at axis'),
    'current': ('MA', 'plasma current'),
    'time': ('s', 'time'),
}
gacode_multi_line_float: Final[Mapping[str, tuple[str, ...]]] = {
    'polflux': ('Wb rad**-1', 'poloidal flux'),
    'q': ('', 'safety factor'),
    'rmin': ('m', 'flux-surface-averaged minor radius'),
    'rmaj': ('m', 'flux-surface-averaged major radius'),
    'zmag': ('m', 'flux-surface-averaged vertical position'),
    'kappa': ('', 'elongation'),
    'delta': ('', 'triangularity'),
    'zeta': ('', 'squareness'),
    'shape_cos': ('', 'cosine shape parameter'),
    'shape_sin': ('', 'sine shape parameter'),
    'ni': ('10**19 m**-3', 'ion density'),
    'ti': ('keV', 'ion temperature'),
    'ne': ('10**19 m**-3', 'electron density'),
    'te': ('keV', 'electron temperature'),
    'z_eff': ('', 'effective charge'),
    'qohme': ('MW m**-3', 'ohmic heating'),
    'qbeame': ('MW m**-3', 'beam heating to electrons'),
    'qbeami': ('MW m**-3', 'beam heating to ions'),
    'qrfe': ('MW m**-3', 'radio frequency heating to electrons'),
    'qrfi': ('MW m**-3', 'radio frequency heating to ions'),
    'qsync': ('MW m**-3', 'synchrotron radiation'),
    'qbrem': ('MW m**-3', 'bremsstrahlung radiation'),
    'qline': ('MW m**-3', 'impurity line radiation'),
    'qfuse': ('MW m**-3', 'fusion power to electrons'),
    'qfusi': ('MW m**-3', 'fusion power to ions'),
    'qei': ('MW m**-3', 'electron-ion energy exchange'),
    'qione': ('MW m**-3', 'ionization energy from electrons'),
    'qioni': ('MW m**-3', 'ionization energy from ions'),
    'qcxi': ('MW m**-3', 'charge exchange energy from ions'),
    'johm': ('MA m**-2', 'ohmic current density'),
    'jbs': ('MA m**-2', 'bootstrap current density'),
    'jbstor': ('MA m**-2', 'toroidal bootstrap current density'),
    'jrf': ('MA m**-2', 'radio frequency induced current density'),
    'jnb': ('MA m**-2', 'neutral beam induced current density'),
    'vtor': ('m s**-1', 'toroidal velocity'),
    'vpol': ('m s**-1', 'poloidal velocity'),
    'omega0': ('rad s**-1', 'toroidal angular frequency'),
    'ptot': ('Pa', 'total pressure'),
    'qpar_beam': ('m**-3 s**-1', 'beam particle source'),
    'qpar_wall': ('m**-3 s**-1', 'wall particle source'),
    'qmom': ('N m**-2', 'momentum source'),
}
gacode_base_variables: Final[Mapping[str, tuple[str, ...]]] = {
    **gacode_single_line_integer,
    **gacode_single_line_string,
    **gacode_single_line_float,
    **gacode_multi_line_float,
}
gacode_unit_strings: Final[Mapping[str, str]] = {
    'torfluxa': 'Wb/radian',
    'rcentr': 'm',
    'bcentr': 'T',
    'current': 'MA',
    'polflux': 'Wb/radian',
    'rmin': 'm',
    'rmaj': 'm',
    'zmag': 'm',
    'ni': '10^19/m^3',
    'ti': 'keV',
    'ne': '10^19/m^3',
    'te': 'keV',
    'qohme': 'MW/m^3',
    'qbeame': 'MW/m^3',
    'qbeami': 'MW/m^3',
    'qrfe': 'MW/m^3',
    'qrfi': 'MW/m^3',
    'qsync': 'MW/m^3',
    'qbrem': 'MW/m^3',
    'qline': 'MW/m^3',
    'qfuse': 'MW/m^3',
    'qfusi': 'MW/m^3',
    'qei': 'MW/m^3',
    'qione': 'MW/m^3',
    'qioni': 'MW/m^3',
    'qcxi': 'MW/m^3',
    'johm': 'MA/m^2',
    'jbs': 'MA/m^2',
    'jbstor': 'MA/m^2',
    'jrf': 'MA/m^2',
    'jnb': 'MA/m^2',
    'vtor': 'm/s',
    'vpol': 'm/s',
    'omega0': 'rad/s',
    'ptot': 'Pa',
    'qpar_beam': '1/m^3/s',
    'qpar_wall': '1/m^3/s',
    'qmom': 'N/m^2',
}


# TORAX full settings list available at https://torax.readthedocs.io/en/v1.3.0/configuration.html
torax_plasma_composition: Final[Mapping[str, Any]] = {
    'main_ion': ('-', 'main ion species'),
    'impurity': ('-', 'impurity species'),
    'Z_eff': ('-', 'effective charge'),
    'Z_i_override': ('-', 'override for ion charge number'),
    'A_i_override': ('-', 'override for ion mass number'),
    'Z_impurity_override': ('-', 'override for impurity charge number'),
    'A_impurity_override': ('-', 'override for impurity mass number'),
}
torax_profile_conditions: Final[Mapping[str, Any]] = {
    'Ip': ('A', 'total plasma current'),
    'use_v_loop_lcfs_boundary_condition': ('', 'toggle LCFS loop voltage as a boundary condition'),
    'v_loop_lcfs': ('V', 'LCFS loop voltage'),
    'T_i': ('keV', 'ion temperature'),
    'T_i_right_bc': ('keV', 'outer boundary condition for ion temperature'),
    'T_e': ('keV', 'electron temperature'),
    'T_e_right_bc': ('keV', 'outer boundary condition for electron temperature'),
    'psi': ('Wb', 'poloidal flux'),
    'n_e': ('m**-3', 'electron density'),
    'normalize_n_e_to_nbar': ('-', 'toggle normalization of electron density to line-averaged electron density'),
    'nbar': ('m**-3', 'line-averaged electron density'),
    'n_e_nbar_is_fGW': ('-', 'toggle whether normalized electron density represents Greenwald fraction'),
    'n_e_right_bc': ('m**-3', 'outer boundary condition for electron density'),
    'n_e_right_bc_is_fGW': ('-', 'toggle whether the outer boundary condition for electron density represents Greenwald fraction'),
    'set_pedestal': ('-', 'toggle inclusion of pedestal models'),
    'current_profile_nu': ('-', 'toggle usage of analytical current profile'),
    'initial_j_is_total_current': ('-', 'toggle whether initial current profile represents total current'),
    'initial_psi_from_j': ('-', 'toggle whether initial poloidal flux is computed from initial current profile'),
}
torax_numerics: Final[Mapping[str, Any]] = {
    't_initial': ('s', 'initial time of simulation'),
    't_final': ('s', 'final time of simulation'),
    'exact_t_final': ('s', 'exact final time of simulation'),
    'evolve_ion_heat': ('-', 'toggle solving of ion energy equation'),
    'evolve_electron_heat': ('-', 'toggle solving of electron energy equation'),
    'evolve_current': ('-', 'toggle solving of poloidal flux equation'),
    'evolve_density': ('-', 'toggle solving of electron continuity equation'),
    'resistivity_multiplier': ('-', 'multiplier for plasma resistivity in poloidal flux evolution equation'),
    'max_dt': ('s', 'maximum time step'),
    'min_dt': ('s', 'minimum time step'),
    'chi_timestep_prefactor': ('-', 'multiplier for chi time step calculator'),
    'fixed_dt': ('s', 'fixed time step'),
    'dt_reduction_factor': ('-', 'reduction factor for time step'),
    'adaptive_T_source_prefactor': ('-', 'prefactor for adaptive ion temperature source'),
    'adaptive_n_source_prefactor': ('-', 'prefactor for adaptive density source'),
}
torax_geometry: Final[Mapping[str, Any]] = {
    'geometry_type': ('-', 'type of geometry'),
    'n_rho': ('-', 'number of radial grid points'),
    'face_centers': ('-', 'rho toroidal flux coordinates to be used as face center radial grid points for non-uniform grids'),
    'hires_factor': ('-', 'high-resolution factor'),
    'cocos': ('-', 'COCOS identifier'),
}
torax_pedestal: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'name of the pedestal model'),
    'set_pedestal': ('-', 'toggle inclusion of pedestal models'),
}
torax_edge: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'name of the edge model'),
}
torax_transport: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'name of the transport model'),
    'chi_min': ('m**2 s**-1', 'minimum chi value'),
    'chi_max': ('m**2 s**-1', 'maximum chi value'),
    'D_e_min': ('m**2 s**-1', 'minimum electron diffusivity'),
    'D_e_max': ('m**2 s**-1', 'maximum electron diffusivity'),
    'V_e_min': ('m s**-1', 'minimum electron velocity'),
    'V_e_max': ('m s**-1', 'maximum electron velocity'),
    'apply_inner_patch': ('-', 'toggle application of inner patch'),
    'D_e_inner': ('m**2 s**-1', 'inner electron diffusivity'),
    'V_e_inner': ('m s**-1', 'inner electron velocity'),
    'chi_i_inner': ('m**2 s**-1', 'inner ion chi value'),
    'chi_e_inner': ('m**2 s**-1', 'inner electron chi value'),
    'rho_inner': ('-', 'inner radial position in rho toroidal flux coordinates'),
    'apply_outer_patch': ('-', 'toggle application of outer patch'),
    'D_e_outer': ('m**2 s**-1', 'outer electron diffusivity'),
    'V_e_outer': ('m s**-1', 'outer electron velocity'),
    'chi_i_outer': ('m**2 s**-1', 'outer ion chi value'),
    'chi_e_outer': ('m**2 s**-1', 'outer electron chi value'),
    'rho_outer': ('-', 'outer radial position in rho toroidal flux coordinates'),
    'smoothing_width': ('-', 'width of smoothing region in rho toroidal flux coordinates'),
    'smooth_everywhere': ('-', 'toggle smoothing everywhere in rho toroidal flux coordinates'),
}
torax_solver: Final[Mapping[str, Any]] = {
    'solver_type': ('-', 'type of solver'),
    'theta_implicit': ('-', 'toggle implicit theta scheme'),
    'use_predictor_corrector': ('-', 'toggle use of predictor-corrector method'),
    'n_corrector_steps': ('-', 'number of corrector steps'),
    'use_pereverzev': ('-', 'toggle use of Pereverzev method'),
    'chi_pereverzev': ('-', 'chi value for Pereverzev method'),
    'D_pereverzev': ('-', 'diffusivity value for Pereverzev method'),
}
torax_time_step_calculator: Final[Mapping[str, Any]] = {
    'calculator_type': ('-', 'type of time step calculator'),
    'tolerance': ('-', 'tolerance for time step calculation'),
}
torax_restart: Final[Mapping[str, Any]] = {
    'filename': ('-', 'restart file name'),
    'time': ('s', 'restart time'),
    'do_restart': ('-', 'toggle restart'),
    'stitch': ('-', 'toggle stitching'),
}

torax_geometry_circular: Final[Mapping[str, Any]] = {
    'R_major': ('m', 'major radius'),
    'a_minor': ('m', 'minor radius'),
    'B_0': ('T', 'magnetic field at magnetic axis'),
    'elongation_LCFS': ('-', 'elongation at LCFS'),
}
torax_geometry_chease: Final[Mapping[str, Any]] = {
    'geometry_file': ('-', 'geometry file name'),
    'geometry_directory': ('-', 'directory containing geometry file'),
    'Ip_from_parameters': ('A', 'plasma current from parameters'),
    'R_major': ('m', 'major radius'),
    'a_minor': ('m', 'minor radius'),
    'B_0': ('T', 'magnetic field at magnetic axis'),
}
torax_geometry_fbt: Final[Mapping[str, Any]] = {
    'geometry_file': ('-', 'geometry file name'),
    'geometry_directory': ('-', 'directory containing geometry file'),
    'Ip_from_parameters': ('A', 'plasma current from parameters'),
    'LY_object': ('-', 'LY object'),
    'LY_bundle_object': ('-', 'LY bundle object'),
    'LY_to_torax_times': ('s', 'times for LY to torax'),
    'L_object': ('-', 'L object'),
}
torax_geometry_eqdsk: Final[Mapping[str, Any]] = {
    'geometry_file': ('-', 'geometry file name'),
    'geometry_directory': ('-', 'directory containing geometry file'),
    'Ip_from_parameters': ('A', 'plasma current from parameters'),
    'n_surfaces': ('-', 'number of surfaces'),
    'last_surface_factor': ('-', 'factor for last surface'),
}
torax_geometry_options: Final[Mapping[str, Any]] = {
    'circular': torax_geometry_circular,
    'chease': torax_geometry_chease,
    'fbt': torax_geometry_fbt,
    'eqdsk': torax_geometry_eqdsk,
}
torax_pedestal_nped_tped: Final[Mapping[str, Any]] = {
    'n_e_ped': ('m**-3', 'electron density at pedestal'),
    'n_e_ped_is_fGW': ('-', 'flag for fGW normalization'),
    'T_i_ped': ('keV', 'ion temperature at pedestal'),
    'T_e_ped': ('keV', 'electron temperature at pedestal'),
    'rho_norm_ped_top': ('-', 'normalized radial position at pedestal top'),
}
torax_pedestal_pped_nped: Final[Mapping[str, Any]] = {
    'P_ped': ('Pa', 'pedestal pressure'),
    'n_e_ped': ('m**-3', 'electron density at pedestal'),
    'n_e_ped_is_fGW': ('-', 'flag for fGW normalization'),
    'T_i_T_e_ratio': ('-', 'ratio of ion to electron temperature'),
    'rho_norm_ped_top': ('-', 'normalized radial position at pedestal top'),
}
torax_pedestal_options: Final[Mapping[str, Any]] = {
    'set_T_ped_n_ped': torax_pedestal_nped_tped,
    'set_P_ped_n_ped': torax_pedestal_pped_nped,
}
torax_neoclassical_bootstrap: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'model name'),
    'bootstrap_multiplier': ('-', 'multiplier for bootstrap current'),
}
torax_neoclassical_transport: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'model name'),
    'chi_min': ('m**2 s**-1', 'minimum neoclassical heat diffusivity'),
    'chi_max': ('m**2 s**-1', 'maximum neoclassical heat diffusivity'),
    'D_e_min': ('m**2 s**-1', 'minimum neoclassical electron diffusivity'),
    'D_e_max': ('m**2 s**-1', 'maximum neoclassical electron diffusivity'),
    'V_e_min': ('m s**-1', 'minimum neoclassical electron velocity'),
    'V_e_max': ('m s**-1', 'maximum neoclassical electron velocity'),
}
torax_neoclassical_conductivity: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'model name'),
}
torax_neoclassical_options: Final[Mapping[str, Any]] = {
    'bootstrap': torax_neoclassical_bootstrap,
    'transport': torax_neoclassical_transport,
    'conductivity': torax_neoclassical_conductivity,
}
torax_mhd_sawtooth: Final[Mapping[str, Any]] = {
    'crash_time_duration': ('s', 'duration of crash phase of sawtooth cycle'),
}
torax_mhd_sawtooth_trigger: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'model name'),
    's_critical': ('-', 'critical safety factor'),
    'minimum_radius': ('m', 'minimum radius'),
}
torax_mhd_sawtooth_redistribution: Final[Mapping[str, Any]] = {
    'model_name': ('-', 'model name'),
    'flattening_factor': ('-', 'flattening factor'),
    'mixing_radius_multiplier': ('-', 'multiplier for mixing radius'),
}
torax_sources_generic_heat: Final[Mapping[str, Any]] = {
    'prescribed_values': ('W m**-3', 'prescribed heat source profiles, ions then electrons if a tuple is provided'),
    'mode': ('-', 'operation mode'),
    'is_explicit': ('-', 'toggle treatment of source as an explicit term in the solver'),
    'gaussian_location': ('m', 'peak location of Gaussian heat deposition profile in rho toroidal flux coordinate'),
    'gaussian_width': ('m', 'width of Gaussian heat deposition profile in rho toroidal flux coordinate'),
    'P_total': ('W', 'total coupled heat power'),
    'electron_heat_fraction': ('-', 'fraction of electron heat'),
    'absorption_fraction': ('-', 'fraction of absorbed power'),
}
torax_sources_generic_particle: Final[Mapping[str, Any]] = {
    'prescribed_values': ('m**-3 s**-1', 'prescribed particle source profiles'),
    'mode': ('-', 'operation mode'),
    'is_explicit': ('-', 'toggle treatment of source as an explicit term in the solver'),
    'deposition_location': ('-', 'peak location of Gaussian particle deposition profile in rho toroidal flux coordinate'),
    'particle_width': ('-', 'width of Gaussian particle deposition profile in rho toroidal flux coordinate'),
    'S_total': ('s**-1', 'total particle injection rate'),
}
torax_sources_generic_current: Final[Mapping[str, Any]] = {
    'prescribed_values': ('A m**-2', 'prescribed current source profiles'),
    'mode': ('-', 'operation mode'),
    'is_explicit': ('-', 'toggle treatment of source as an explicit term in the solver'),
    'gaussian_location': ('-', 'peak location of Gaussian current deposition profile in rho toroidal flux coordinate'),
    'gaussian_width': ('-', 'width of Gaussian current deposition profile in rho toroidal flux coordinate'),
    'I_generic': ('A', 'total current deposited by source'),
    'fraction_of_total_current': ('-', 'set current source as a fraction of total current'),
    'use_absolute_current': ('-', 'toggle use of absolute current'),
}
torax_sources_ei_exchange: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'Qei_multiplier',
}
torax_sources_ohmic: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
}
torax_sources_fusion: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
}
torax_sources_gas_puff: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'puff_decay_length',
    'S_total',
}
torax_sources_pellet: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'pellet_deposition_location',
    'pellet_width',
    'S_total',
}
torax_sources_bremsstrahlung: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'use_relativistic_correction',
}
torax_sources_impurity_radiation: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'model_name',
}
torax_sources_cyclotron_radiation: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'wall_reflection_coeff',
    'beta_min',
    'beta_max',
    'beta_grid_size',
}
torax_sources_ecrh: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'extra_prescribed_power_density',
    'gaussian_location',
    'gaussian_width',
    'P_total',
    'current_drive_efficiency',
}
torax_sources_icrh: Final[Mapping[str, Any]] = {
    'prescribed_values',
    'mode',
    'is_explicit',
    'model_path',
    'wall_inner',
    'wall_outer',
    'frequency',
    'minority_concentration',
    'P_total',
}
torax_transport_constant: Final[Mapping[str, Any]] = {
    'chi_i',
    'chi_e',
    'D_e',
    'V_e',
}
torax_transport_cgm: Final[Mapping[str, Any]] = {
    'alpha',
    'chi_stiff',
    'chi_e_i_ratio',
    'chi_D_ratio',
    'VR_D_ratio',
}
torax_transport_bohm_gyrobohm: Final[Mapping[str, Any]] = {
    'chi_e_bohm_coeff',
    'chi_e_gyrobohm_coeff',
    'chi_i_bohm_coeff',
    'chi_i_gyrobohm_coeff',
    'chi_e_bohm_multiplier',
    'chi_e_gyrobohm_multiplier',
    'chi_i_bohm_multiplier',
    'chi_i_gyrobohm_multiplier',
    'D_face_c1',
    'D_face_c2',
    'V_face_coeff',
}
torax_transport_qlknn: Final[Mapping[str, Any]] = {
    'model_path',
    'qlknn_model_name',
    'include_ITG',
    'include_TEM',
    'include_ETG',
    'ITG_flux_ratio_correction',
    'ETG_correction_factor',
    'clip_inputs',
    'clip_margin',
    'collisionality_multiplier',
    'DV_effective',
    'An_min',
    'avoid_big_negative_s',
    'smag_alpha_correction',
    'q_sawtooth_proxy',
}
torax_transport_qualikiz: Final[Mapping[str, Any]] = {
    'n_max_runs',
    'n_processes',
    'collisionality_multiplier',
    'DV_effective',
    'An_min',
    'avoid_big_negative_s',
    'smag_alpha_correction',
    'q_sawtooth_proxy',
}
torax_solver_linear: Final[Mapping[str, Any]] = {
}
torax_solver_newton_raphson: Final[Mapping[str, Any]] = {
    'log_iterations',
    'initial_guess_mode',
    'residual_tol',
    'residual_coarse_tol',
    'n_max_iterations',
    'delta_reduction_factor',
    'tau_min',
}
torax_solver_optimizer: Final[Mapping[str, Any]] = {
    'initial_guess_mode',
    'loss_tol',
    'n_max_iterations',
}
torax_solver_options: Final[Mapping[str, Any]] = {
    'linear': torax_solver_linear,
    'newton_raphson': torax_solver_newton_raphson,
    'optimizer': torax_solver_optimizer,
}
torax_allowed_radiation_species: Final[Sequence[str]] = [
    'H',
    'D',
    'T',
    'He3',
    'He4',
    'Li',
    'Be',
    'C',
    'N',
    'O',
    'N',
    'O',
    'Ne',
    'Ar',
    'Kr',
    'Xe',
    'W',
]


# Full IMAS data dictionary scheme available at https://imas-data-dictionary.readthedocs.io/
imas_ids_top_levels: Final[Sequence[str]] = [
    'amns_data',
    'barometry',
    'b_field_non_axisymmetric',
    'bolometer',
    'bremsstrahlung_visible',
    'camera_ir',
    'camera_visible',
    'camera_x_rays',
    'charge_exchange',
    'coils_non_axisymmetric',
    'controllers',
    'core_instant_changes',
    'core_profiles',
    'core_sources',
    'core_transport',
    'cryostat',
    'dataset_description',
    'dataset_fair',
    'disruption',
    'distributions_sources',
    'distributions',
    'divertors',
    'ec_launchers',
    'ece',
    'edge_profiles',
    'edge_sources',
    'edge_transport',
    'em_coupling',
    'equilibrium',
    'ferritic',
    'focs',
    'gas_injection',
    'gas_pumping',
    'gyrokinetics_local',
    'hard_x_rays',
    'ic_antennas',
    'interferometer',
    'iron_core',
    'langmuir_probes',
    'lh_antennas',
    'magnetics',
    'operational_instrumentation',
    'mhd',
    'mhd_linear',
    'mse',
    'nbi',
    'neutron_diagnostic',
    'ntms',
    'pellets',
    'pf_active',
    'pf_passive',
    'pf_plasma',
    'plasma_initiation',
    'plasma_profiles',
    'plasma_sources',
    'plasma_transport',
    'polarimeter',
    'pulse_schedule',
    'radiation',
    'real_time_data',
    'reflectometer_profile',
    'reflectometer_fluctuation',
    'refractometer',
    'runaway_electrons',
    'sawteeth',
    'soft_x_rays',
    'spectrometer_mass',
    'spectrometer_uv',
    'spectrometer_visible',
    'spectrometer_x_ray_crystal',
    'spi',
    'summary',
    'temporary',
    'thomson_scattering',
    'tf',
    'transport_solver_numerics',
    'turbulence',
    'wall',
    'waves',
    'workflow',
]
imas_source_names: Final[Sequence[str]] = [
    'total',
    'nbi',
    'ec',
    'lh',
    'ic',
    'fusion',
    'ohmic',
    'bremsstrahlung',
    'synchrotron_radiation',
    'line_radiation',
    'collisional_equipartition',
    'cold_neutrals',
    'bootstrap_current',
    'pellet',
    'auxiliary',
    'ic_nbi',
    'ic_fusion',
    'ic_nbi_fusion',
    'ec_lh',
    'ec_ic',
    'lh_ic',
    'ec_lh_ic',
    'gas_puff',
    'killer_gas_puff',
    'radiation',
    'cyclotron_radiation',
    'cyclotron_synchrotron_radiation',
    'impurity_radiation',
    'particles_to_wall',
    'particles_to_pump',
    'charge_exchange',
    'transport',
    'neoclassical',
    'equipartition',
    'turbulent_equipartition',
    'runaways',
    'ionisation',
    'recombination',
    'excitation',
    'database',
    'gaussian',
]